DROP TABLE IF EXISTS "secret_channel_users" CASCADE;
DROP TABLE IF EXISTS "channel_rating" CASCADE;
DROP TABLE IF EXISTS "likes" CASCADE;
DROP TABLE IF EXISTS "messages" CASCADE;
DROP TABLE IF EXISTS "threads" CASCADE;
DROP TABLE IF EXISTS "channels" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "secret_channel_users" CASCADE;